import type { AssetType } from '@lifenomics/shared/schemas'

import { type AssetTag, assetTags } from './assetTags'
import { type Exchange, exchanges } from './exchanges'
import { type Industry, industries } from './industries'

export type Asset = {
	exchange: Exchange
	type: AssetType
	industry: Industry
	tags: AssetTag[]
	isActive: boolean
	isin?: string
	ticker: string
	name: string
	shortName?: string
	class?: 'A' | 'B' | 'C'
	adr?: boolean
	description?: string
	imageUrl?: string
	website?: string
}

export const assets = {
	CH0012221716: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.electricalEquipmentParts,
		tags: [assetTags.technology, assetTags.industry, assetTags.robotics],
		isActive: true,
		isin: 'CH0012221716',
		ticker: 'ABB',
		name: 'ABB Ltd',
		shortName: 'ABB',
		description: '',
		imageUrl: '',
		website: 'https://global.abb/group/en',
	},
	NL0010273215: {
		exchange: exchanges.AMSTERDAM,
		type: 'stock',
		industry: industries.semiconductorEquipmentMaterials,
		tags: [
			assetTags.semiconductors,
			assetTags.industry,
			assetTags.technology,
			assetTags.hardware,
		],
		isActive: true,
		isin: 'NL0010273215',
		ticker: 'ASML',
		name: 'ASML Holding N.V.',
		shortName: 'ASML Holding',
		description: '',
		imageUrl: '',
		website: 'https://www.asml.com/en',
	},
	FR0000120628: {
		exchange: exchanges.PARIS,
		type: 'stock',
		industry: industries.insuranceDiversified,
		tags: [assetTags.insurance, assetTags.finance],
		isActive: true,
		isin: 'FR0000120628',
		ticker: 'CS',
		name: 'AXA SA',
		shortName: 'AXA',
		description: '',
		imageUrl: '',
		website: 'https://www.axa.com/',
	},
	US0079031078: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
		isActive: true,
		isin: 'US0079031078',
		ticker: 'AMD',
		name: 'Advanced Micro Devices, Inc.',
		shortName: 'Advanced Micro Devices',
		description: '',
		imageUrl: '',
		website: 'https://www.amd.com/en.html',
	},
	US0090661010: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.travelServices,
		tags: [assetTags.technology, assetTags.software, assetTags.travel],
		isActive: true,
		isin: 'US0090661010',
		ticker: 'ABNB',
		name: 'Airbnb, Inc.',
		shortName: 'Airbnb',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://www.airbnb.com/',
	},
	NL0000235190: {
		exchange: exchanges.PARIS,
		type: 'stock',
		industry: industries.aerospaceDefense,
		tags: [
			assetTags.industry,
			assetTags.defense,
			assetTags.technology,
			assetTags.commercialVehicles,
		],
		isActive: true,
		isin: 'NL0000235190',
		ticker: 'AIR',
		name: 'Airbus SE',
		shortName: 'Airbus',
		description: '',
		imageUrl: '',
		website: 'https://www.airbus.com/en',
	},
	US01609W1027: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.eCommerce,
			assetTags.consumer,
			assetTags.cloud,
			assetTags.ai,
		],
		isActive: true,
		isin: 'US01609W1027',
		ticker: 'BABA',
		name: 'Alibaba Group Holding Limited',
		shortName: 'Alibaba Group',
		description: '',
		imageUrl: '',
		website: 'https://www.alibabagroup.com/en-US/',
	},
	US02079K3059: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.internetContentInformation,
		tags: [assetTags.technology, assetTags.software, assetTags.cloud],
		isActive: true,
		isin: 'US02079K3059',
		ticker: 'GOOGL',
		name: 'Alphabet Inc.',
		shortName: 'Alphabet',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://abc.xyz/',
	},
	US0231351067: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.cloud,
			assetTags.eCommerce,
		],
		isActive: true,
		isin: 'US0231351067',
		ticker: 'AMZN',
		name: 'Amazon.com, Inc.',
		shortName: 'Amazon.com',
		description: '',
		imageUrl: '',
		website: 'https://www.aboutamazon.com/',
	},
	US0378331005: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.consumerElectronics,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.cloud,
			assetTags.consumer,
			assetTags.hardware,
		],
		isActive: true,
		isin: 'US0378331005',
		ticker: 'AAPL',
		name: 'Apple Inc.',
		shortName: 'Apple',
		description: '',
		imageUrl: '',
		website: 'https://www.apple.com',
	},
	US0382221051: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
		isActive: true,
		isin: 'US0382221051',
		ticker: 'AMAT',
		name: 'Applied Materials, Inc.',
		shortName: 'Applied Materials',
		description: '',
		imageUrl: '',
		website: 'https://www.appliedmaterials.com/us/en.html',
	},
	GB0009895292: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.drugManufacturersGeneral,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.healthcare,
		],
		isActive: true,
		isin: 'GB0009895292',
		ticker: 'AZN',
		name: 'AstraZeneca PLC',
		shortName: 'AstraZeneca',
		description: '',
		imageUrl: '',
		website: 'https://www.astrazeneca.com',
	},
	SE0017486897: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.technology],
		isActive: true,
		isin: 'SE0017486897',
		ticker: 'ATCO-B',
		name: 'Atlas Copco AB',
		shortName: 'Atlas Copco',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.atlascopcogroup.com/',
	},
	CA05156X8504: {
		exchange: exchanges.TORONTO,
		type: 'stock',
		industry: industries.drugManufacturersSpecialtyGeneric,
		tags: [assetTags.cannabis, assetTags.pharmaceuticals],
		isActive: true,
		isin: 'CA05156X8504',
		ticker: 'ACB',
		name: 'Aurora Cannabis Inc.',
		shortName: 'Aurora Cannabis',
		description: '',
		imageUrl: '',
		website: 'https://www.auroramj.com/investors/',
	},
	SE0012454072: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.banksRegional,
		tags: [assetTags.finance, assetTags.banking],
		isActive: true,
		isin: 'SE0012454072',
		ticker: 'AZA',
		name: 'Avanza Bank Holding AB',
		shortName: 'Avanza Bank',
		description: '',
		imageUrl: '',
		website: 'https://www.avanza.se',
	},
	SE0006993770: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.groceryStores,
		tags: [assetTags.consumer],
		isActive: true,
		isin: 'SE0006993770',
		ticker: 'AXFO',
		name: 'Axfood AB',
		shortName: 'Axfood',
		description: '',
		imageUrl: '',
		website: 'https://www.axfood.com/',
	},
	SE0010442418: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.telecomServices,
		tags: [assetTags.consumer, assetTags.telecom],
		isActive: true,
		isin: 'SE0010442418',
		ticker: 'BAHN-B',
		name: 'Bahnhof AB',
		shortName: 'Bahnhof',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://bahnhof.se',
	},
	CA0641491075: {
		exchange: exchanges.TORONTO,
		type: 'stock',
		industry: industries.banksDiversified,
		tags: [assetTags.finance, assetTags.banking],
		isActive: true,
		isin: 'CA0641491075',
		ticker: 'BNS',
		name: 'The Bank of Nova Scotia',
		shortName: 'Bank of Nova Scotia',
		description: '',
		imageUrl: '',
		website: 'https://www.scotiabank.com',
	},
	SE0010323311: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.biotechnology,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.healthcare,
		],
		isActive: true,
		isin: 'SE0010323311',
		ticker: 'BIOA-B',
		name: 'BioArctic AB',
		shortName: 'BioArctic',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.bioarctic.com/en/',
	},
	US8522341036: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.softwareInfrastructure,
		tags: [
			assetTags.banking,
			assetTags.finance,
			assetTags.technology,
			assetTags.crypto,
			assetTags.software,
			assetTags.payments,
		],
		isActive: true,
		isin: 'US8522341036',
		ticker: 'XYZ',
		name: 'Block, Inc.',
		shortName: 'Block',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://block.xyz/',
	},
	US11135F1012: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
			assetTags.dataCenter,
		],
		isActive: true,
		isin: 'US11135F1012',
		ticker: 'AVGO',
		name: 'Broadcom Inc.',
		shortName: 'Broadcom',
		description: '',
		imageUrl: '',
		website: 'https://www.broadcom.com',
	},
	CA13321L1085: {
		exchange: exchanges.TORONTO,
		type: 'stock',
		industry: industries.uranium,
		tags: [assetTags.energy, assetTags.mining, assetTags.nuclearEnergy],
		isActive: true,
		isin: 'CA13321L1085',
		ticker: 'CCO',
		name: 'Cameco Corporation',
		shortName: 'Cameco',
		description: '',
		imageUrl: '',
		website: 'https://www.cameco.com',
	},
	CA1363751027: {
		exchange: exchanges.TORONTO,
		type: 'stock',
		industry: industries.railroads,
		tags: [
			assetTags.transportation,
			assetTags.railroads,
			assetTags.logistics,
		],
		isActive: true,
		isin: 'CA1363751027',
		ticker: 'CNR',
		name: 'Canadian National Railway Company',
		shortName: 'Canadian National Railway',
		description: '',
		imageUrl: '',
		website: 'https://www.cn.ca/en/',
	},
	CA13646K1084: {
		exchange: exchanges.TORONTO,
		type: 'stock',
		industry: industries.railroads,
		tags: [
			assetTags.transportation,
			assetTags.railroads,
			assetTags.logistics,
		],
		isActive: true,
		isin: 'CA13646K1084',
		ticker: 'CP',
		name: 'Canadian Pacific Kansas City Limited',
		shortName: 'Canadian Pacific Kansas City',
		description: '',
		imageUrl: '',
		website: 'https://www.cpkcr.com/en',
	},
	SE0015810502: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.softwareApplication,
		tags: [assetTags.technology, assetTags.software],
		isActive: true,
		isin: 'SE0015810502',
		ticker: 'CHECK',
		name: 'Checkin.com Group AB',
		shortName: 'Checkin.com Group',
		description: '',
		imageUrl: '',
		website: 'https://group.checkin.com/',
	},
	SE0000584948: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.specialtyRetail,
		tags: [assetTags.consumer, assetTags.retail],
		isActive: true,
		isin: 'SE0000584948',
		ticker: 'CLAS-B',
		name: 'Clas Ohlson AB',
		shortName: 'Clas Ohlson',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.clasohlson.com/',
	},
	SE0002626861: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.confectioners,
		tags: [assetTags.consumer, assetTags.foodAndBeverages],
		isActive: true,
		isin: 'SE0002626861',
		ticker: 'CLA-B',
		name: 'Cloetta AB',
		shortName: 'Cloetta',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.cloetta.com',
	},
	US1912161007: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.beveragesNonAlcoholic,
		tags: [assetTags.consumer, assetTags.foodAndBeverages],
		isActive: true,
		isin: 'US1912161007',
		ticker: 'KO',
		name: 'The Coca-Cola Company',
		shortName: 'Coca-Cola',
		description: '',
		imageUrl: '',
		website: 'https://www.coca-colacompany.com',
	},
	US19260Q1076: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.financialDataStockExchanges,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.finance,
			assetTags.crypto,
		],
		isActive: true,
		isin: 'US19260Q1076',
		ticker: 'COIN',
		name: 'Coinbase Global, Inc.',
		shortName: 'Coinbase',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://www.coinbase.com',
	},
	US22266T1097: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.eCommerce,
			assetTags.consumer,
		],
		isActive: true,
		isin: 'US22266T1097',
		ticker: 'CPNG',
		name: 'Coupang, Inc.',
		shortName: 'Coupang',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://www.aboutcoupang.com',
	},
	SE0015661236: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.assetManagement,
		tags: [assetTags.investmentCompanies, assetTags.finance],
		isActive: true,
		isin: 'SE0015661236',
		ticker: 'CRED-A',
		name: 'Creades AB',
		shortName: 'Creades',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://www.creades.se',
	},
	SE0020975852: {
		exchange: exchanges.SPOTLIGHT,
		type: 'stock',
		industry: industries.pollutionTreatmentControls,
		tags: [
			assetTags.technology,
			assetTags.wasteAndRecycling,
			assetTags.biotechnology,
			assetTags.materials,
			assetTags.industry,
		],
		isActive: true,
		isin: 'SE0020975852',
		ticker: 'CYCLE',
		name: 'Cyclezyme AB',
		shortName: 'Cyclezyme',
		description: '',
		imageUrl: '',
		website: 'https://www.cyclezyme.se/',
	},
	CZ1008000310: {
		exchange: exchanges.PRAGUE,
		type: 'stock',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.technology],
		isActive: true,
		isin: 'CZ1008000310',
		ticker: 'DSPW',
		name: 'Doosan Skoda Power',
		shortName: 'Doosan Skoda Power',
		description: '',
		imageUrl: '',
		website: 'https://www.doosanskodapower.com/',
	},
	FI0009007132: {
		exchange: exchanges.HELSINKI,
		type: 'stock',
		industry: industries.utilitiesRegulatedElectric,
		tags: [assetTags.energy, assetTags.utilities, assetTags.nuclearEnergy],
		isActive: true,
		isin: 'FI0009007132',
		ticker: 'FORTUM',
		name: 'Fortum Oyj',
		shortName: 'Fortum',
		description: '',
		imageUrl: '',
		website: 'https://www.fortum.com/Investors',
	},
	SE0000202624: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.medicalDevices,
		tags: [assetTags.healthcare, assetTags.technology],
		isActive: true,
		isin: 'SE0000202624',
		ticker: 'GETI-B',
		name: 'Getinge AB',
		shortName: 'Getinge',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.getinge.com',
	},
	KYG4124C1096: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.softwareApplication,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.transportation,
		],
		isActive: true,
		isin: 'KYG4124C1096',
		ticker: 'GRAB',
		name: 'Grab Holdings Limited',
		shortName: 'Grab',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://www.grab.com/sg',
	},
	SE0015961909: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.scientificTechnicalInstruments,
		tags: [assetTags.industry, assetTags.technology],
		isActive: true,
		isin: 'SE0015961909',
		ticker: 'HEXA-B',
		name: 'Hexagon AB',
		shortName: 'Hexagon',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.hexagon.com',
	},
	SE0018040677: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.communicationEquipment,
		tags: [assetTags.technology, assetTags.telecommunications],
		isActive: true,
		isin: 'SE0018040677',
		ticker: 'HTRO',
		name: 'Hexatronic Group AB',
		shortName: 'Hexatronic Group',
		description: '',
		imageUrl: '',
		website: 'https://www.hexatronic.com',
	},
	US4330001060: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.householdPersonalProducts,
		tags: [assetTags.healthcare, assetTags.pharmaceuticals],
		isActive: true,
		isin: 'US4330001060',
		ticker: 'HIMS',
		name: 'Hims & Hers Health, Inc.',
		shortName: 'Hims & Hers Health',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://investors.hims.com/overview/default.aspx',
	},
	FI0009000459: {
		exchange: exchanges.HELSINKI,
		type: 'stock',
		industry: industries.packagingContainers,
		tags: [
			assetTags.consumer,
			assetTags.foodAndBeverages,
			assetTags.paperAndForestProducts,
		],
		isActive: true,
		isin: 'FI0009000459',
		ticker: 'HUH1V',
		name: 'Huhtamäki Oyj',
		shortName: 'Huhtamäki',
		description: '',
		imageUrl: '',
		website: 'https://www.huhtamaki.com/en/',
	},
	SE0015811963: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.assetManagement,
		tags: [assetTags.investmentCompanies, assetTags.finance],
		isActive: true,
		isin: 'SE0015811963',
		ticker: 'INVE-B',
		name: 'Investor AB',
		shortName: 'Investor',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.investorab.com',
	},
	FI0009013403: {
		exchange: exchanges.HELSINKI,
		type: 'stock',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.technology],
		isActive: true,
		isin: 'FI0009013403',
		ticker: 'KNEBV',
		name: 'Kone Oyj',
		shortName: 'Kone',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.kone.com/en/investors/',
	},
	US5006311063: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.utilitiesRegulatedElectric,
		tags: [assetTags.energy, assetTags.utilities, assetTags.nuclearEnergy],
		isActive: true,
		isin: 'US5006311063',
		ticker: 'KEP',
		name: 'Korea Electric Power Corporation',
		shortName: 'Korea Electric Power',
		adr: true,
		description: '',
		imageUrl: '',
		website: 'https://home.kepco.co.kr/',
	},
	CA5503721063: {
		exchange: exchanges.TORONTO,
		type: 'stock',
		industry: industries.copper,
		tags: [assetTags.mining, assetTags.materials],
		isActive: true,
		isin: 'CA5503721063',
		ticker: 'LUMI',
		name: 'Lundin Mining Corporation',
		shortName: 'Lundin Mining Corporation',
		description: '',
		imageUrl: '',
		website: 'https://www.lundinmining.com/',
	},
	US57142B1044: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.softwareInfrastructure,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.finance,
			assetTags.crypto,
			assetTags.payments,
		],
		isActive: true,
		isin: 'US57142B1044',
		ticker: 'MQ',
		name: 'Marqeta, Inc.',
		shortName: 'Marqeta',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://www.marqeta.com',
	},
	US30303M1027: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.internetContentInformation,
		tags: [assetTags.technology, assetTags.software],
		isActive: true,
		isin: 'US30303M1027',
		ticker: 'META',
		name: 'Meta Platforms, Inc.',
		shortName: 'Meta Platforms',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://investor.atmeta.com/',
	},
	US5951121038: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
		isActive: true,
		isin: 'US5951121038',
		ticker: 'MU',
		name: 'Micron Technology, Inc.',
		shortName: 'Micron Technology',
		description: '',
		imageUrl: '',
		website: 'https://www.micron.com',
	},
	US5949181045: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.softwareInfrastructure,
		tags: [assetTags.technology, assetTags.software, assetTags.cloud],
		isActive: true,
		isin: 'US5949181045',
		ticker: 'MSFT',
		name: 'Microsoft Corporation',
		shortName: 'Microsoft',
		description: '',
		imageUrl: '',
		website: 'https://www.microsoft.com',
	},
	SE0009216278: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.leisure,
		tags: [assetTags.hardware, assetTags.technology, assetTags.consumer],
		isActive: true,
		isin: 'SE0009216278',
		ticker: 'MIPS',
		name: 'Mips AB',
		shortName: 'Mips',
		description: '',
		imageUrl: '',
		website: 'https://mipscorp.com/',
	},
	US67066G1040: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
		isActive: true,
		isin: 'US67066G1040',
		ticker: 'NVDA',
		name: 'NVIDIA Corporation',
		shortName: 'NVIDIA',

		description: '',
		imageUrl: '',
		website: 'https://www.nvidia.com/en-us/',
	},
	US6541061031: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.footwearAccessories,
		tags: [assetTags.consumer, assetTags.fashion],
		isActive: true,
		isin: 'US6541061031',
		ticker: 'NKE',
		name: 'Nike, Inc.',
		shortName: 'Nike',
		description: '',
		imageUrl: '',
		website: 'https://www.nike.com',
	},
	SE0017831795: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.banksRegional,
		tags: [assetTags.banking, assetTags.finance],
		isActive: true,
		isin: 'SE0017831795',
		ticker: 'NORION',
		name: 'Norion Bank AB',
		shortName: 'Norion Bank',
		description: '',
		imageUrl: '',
		website: 'https://norionbank.se/',
	},
	DK0062498333: {
		exchange: exchanges.COPENHAGEN,
		type: 'stock',
		industry: industries.drugManufacturersGeneral,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.healthcare,
		],
		isActive: true,
		isin: 'DK0062498333',
		ticker: 'NOVO-B',
		name: 'Novo Nordisk A/S',
		shortName: 'Novo Nordisk',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.novonordisk.com/',
	},
	KYG6683N1034: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.banksRegional,
		tags: [
			assetTags.banking,
			assetTags.finance,
			assetTags.payments,
			assetTags.fintech,
		],
		isActive: true,
		isin: 'KYG6683N1034',
		ticker: 'NU',
		name: 'Nu Holdings Ltd.',
		shortName: 'Nu Holdings',
		description: '',
		imageUrl: '',
		website: 'https://www.investidores.nu/en/',
	},
	US68373M1071: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.internetContentInformation,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.fintech,
			assetTags.crypto,
		],
		isActive: true,
		isin: 'US68373M1071',
		ticker: 'OPRA',
		name: 'Opera Limited',
		shortName: 'Opera',
		adr: true,
		description: '',
		imageUrl: '',
		website: 'https://www.opera.com',
	},
	NO0003733800: {
		exchange: exchanges.OSLO,
		type: 'stock',
		industry: industries.packagedFoods,
		tags: [assetTags.consumer, assetTags.foodAndBeverages],
		isActive: true,
		isin: 'NO0003733800',
		ticker: 'ORK',
		name: 'Orkla ASA',
		shortName: 'Orkla',
		description: '',
		imageUrl: '',
		website: 'https://www.orkla.com/',
	},
	DE000PAH0038: {
		exchange: exchanges.XETRA,
		type: 'stock',
		industry: industries.autoManufacturers,
		tags: [assetTags.automotive, assetTags.industry, assetTags.consumer],
		isActive: true,
		isin: 'DE000PAH0038',
		ticker: 'PAH3',
		name: 'Porsche Automobil Holding SE',
		shortName: 'Porsche Automobil Holding',
		description: '',
		imageUrl: '',
		website: 'https://www.porsche-se.com/en/',
	},
	US7475251036: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
		isActive: true,
		isin: 'US7475251036',
		ticker: 'QCOM',
		name: 'QUALCOMM Incorporated',
		shortName: 'QUALCOMM',
		description: '',
		imageUrl: '',
		website: 'https://www.qualcomm.com',
	},
	US76954A1034: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.autoManufacturers,
		tags: [assetTags.automotive, assetTags.industry, assetTags.consumer],
		isActive: true,
		isin: 'US76954A1034',
		ticker: 'RIVN',
		name: 'Rivian Automotive, Inc.',
		shortName: 'Rivian Automotive',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://rivian.com/',
	},
	US7707001027: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.capitalMarkets,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.finance,
			assetTags.crypto,
			assetTags.fintech,
		],
		isActive: true,
		isin: 'US7707001027',
		ticker: 'HOOD',
		name: 'Robinhood Markets, Inc.',
		shortName: 'Robinhood Markets',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://robinhood.com/',
	},
	IE00BYTBXV33: {
		exchange: exchanges.DUBLIN,
		type: 'stock',
		industry: industries.airlines,
		tags: [assetTags.transportation, assetTags.travel],
		isActive: true,
		isin: 'IE00BYTBXV33',
		ticker: 'RYA',
		name: 'Ryanair Holdings plc',
		shortName: 'Ryanair',
		description: '',
		imageUrl: '',
		website: 'https://www.ryanair.com/',
	},
	SE0021921269: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.aerospaceDefense,
		tags: [assetTags.industry, assetTags.technology, assetTags.defense],
		isActive: true,
		isin: 'SE0021921269',
		ticker: 'SAAB-B',
		name: 'Saab AB',
		shortName: 'SAAB',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.saab.com/',
	},
	SE0000108227: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.toolsAccessories,
		tags: [assetTags.industry],
		isActive: true,
		isin: 'SE0000108227',
		ticker: 'SKF-B',
		name: 'AB SKF',
		shortName: 'SKF',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.skf.com/',
	},
	SE0015346895: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.softwareApplication,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.fintech,
			assetTags.crypto,
		],
		isActive: true,
		isin: 'SE0015346895',
		ticker: 'SFL',
		name: 'Safello Group AB',
		shortName: 'Safello Group',
		description: '',
		imageUrl: '',
		website: 'https://safello.com/',
	},
	US79466L3024: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.softwareApplication,
		tags: [assetTags.technology, assetTags.software],
		isActive: true,
		isin: 'US79466L3024',
		ticker: 'CRM',
		name: 'Salesforce, Inc.',
		shortName: 'Salesforce',
		description: '',
		imageUrl: '',
		website: 'https://www.salesforce.com/',
	},
	SE0000667891: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.mining],
		isActive: true,
		isin: 'SE0000667891',
		ticker: 'SAND',
		name: 'Sandvik AB',
		shortName: 'Sandvik',
		description: '',
		imageUrl: '',
		website: 'https://www.home.sandvik/',
	},
	US81141R1005: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.fintech,
			assetTags.eCommerce,
			assetTags.payments,
			assetTags.gaming,
		],
		isActive: true,
		isin: 'US81141R1005',
		ticker: 'SE',
		name: 'Sea Limited',
		shortName: 'Sea',
		class: 'A',
		adr: true,
		description: '',
		imageUrl: '',
		website: 'https://www.sea.com/',
	},
	SE0010219626: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.diagnosticsResearch,
		tags: [
			assetTags.technology,
			assetTags.healthcare,
			assetTags.medicalDevices,
		],
		isActive: true,
		isin: 'SE0010219626',
		ticker: 'SENZA',
		name: 'SenzaGen AB',
		shortName: 'SenzaGen',
		description: '',
		imageUrl: '',
		website: 'https://senzagen.com/',
	},
	CA82509L1076: {
		exchange: exchanges.TORONTO,
		type: 'stock',
		industry: industries.softwareApplication,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.eCommerce,
			assetTags.payments,
		],
		isActive: true,
		isin: 'CA82509L1076',
		ticker: 'SHOP',
		name: 'Shopify Inc.',
		shortName: 'Shopify',
		description: '',
		imageUrl: '',
		website: 'https://www.shopify.com/',
	},
	SE0000113250: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.engineeringConstruction,
		tags: [assetTags.construction],
		isActive: true,
		isin: 'SE0000113250',
		ticker: 'SKA-B',
		name: 'Skanska AB',
		shortName: 'Skanska',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://group.skanska.com/',
	},
	SE0012141687: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.resortsCasinos,
		tags: [
			assetTags.travel,
			assetTags.consumer,
			assetTags.entertainment,
			assetTags.sports,
			assetTags.hotelAndRestaurants,
			assetTags.skiing,
		],
		isActive: true,
		isin: 'SE0012141687',
		ticker: 'SKIS',
		name: 'SkiStar AB',
		shortName: 'SkiStar',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.skistar.com/',
	},
	US8740391003: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.industry,
			assetTags.technology,
			assetTags.hardware,
		],
		isActive: true,
		isin: 'US8740391003',
		ticker: 'TSM',
		name: 'Taiwan Semiconductor Manufacturing Company Limited',
		shortName: 'Taiwan Semicond Mfg Co',
		adr: true,
		description: '',
		imageUrl: '',
		website: 'https://www.tsmc.com/english',
	},
	NO0010063308: {
		exchange: exchanges.OSLO,
		type: 'stock',
		industry: industries.telecomServices,
		tags: [assetTags.telecom],
		isActive: true,
		isin: 'NO0010063308',
		ticker: 'TEL',
		name: 'Telenor ASA',
		shortName: 'Telenor',
		description: '',
		imageUrl: '',
		website: 'https://www.telenor.com/',
	},
	US88160R1014: {
		exchange: exchanges.NASDAQ,
		type: 'stock',
		industry: industries.autoManufacturers,
		tags: [
			assetTags.automotive,
			assetTags.consumer,
			assetTags.technology,
			assetTags.robotics,
		],
		isActive: true,
		isin: 'US88160R1014',
		ticker: 'TSLA',
		name: 'Tesla, Inc.',
		shortName: 'Tesla',
		description: '',
		imageUrl: '',
		website: 'https://www.tesla.com/',
	},
	SE0006422390: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.leisure,
		tags: [assetTags.automotive, assetTags.consumer],
		isActive: true,
		isin: 'SE0006422390',
		ticker: 'THULE',
		name: 'Thule Group AB',
		shortName: 'Thule Group',
		description: '',
		imageUrl: '',
		website: 'https://www.thulegroup.com/',
	},
	NO0012470089: {
		exchange: exchanges.OSLO,
		type: 'stock',
		industry: industries.wasteManagement,
		tags: [assetTags.technology, assetTags.wasteAndRecycling],
		isActive: true,
		isin: 'NO0012470089',
		ticker: 'TOM',
		name: 'Tomra Systems ASA',
		shortName: 'Tomra Systems',
		description: '',
		imageUrl: '',
		website: 'https://www.tomra.com/',
	},
	CH0244767585: {
		exchange: exchanges.SWISS,
		type: 'stock',
		industry: industries.banksDiversified,
		tags: [assetTags.banking, assetTags.finance],
		isActive: true,
		isin: 'CH0244767585',
		ticker: 'UBSG',
		name: 'UBS Group AG',
		shortName: 'UBS Group',
		description: '',
		imageUrl: '',
		website: 'https://www.ubs.com/',
	},
	US90353T1007: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.softwareApplication,
		tags: [assetTags.technology, assetTags.software],
		isActive: true,
		isin: 'US90353T1007',
		ticker: 'UBER',
		name: 'Uber Technologies, Inc.',
		shortName: 'Uber',
		description: '',
		imageUrl: '',
		website: 'https://www.uber.com',
	},
	SE0000115446: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.farmHeavyConstructionMachinery,
		tags: [assetTags.industry, assetTags.commercialVehicles],
		isActive: true,
		isin: 'SE0000115446',
		ticker: 'VOLV-B',
		name: 'AB Volvo',
		shortName: 'Volvo',
		class: 'B',
		description: '',
		imageUrl: '',
		website: 'https://www.volvogroup.com/',
	},
	US9311421039: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.discountStores,
		tags: [
			assetTags.retail,
			assetTags.consumer,
			assetTags.foodAndBeverages,
		],
		isActive: true,
		isin: 'US9311421039',
		ticker: 'WMT',
		name: 'Walmart Inc.',
		shortName: 'Walmart',
		description: '',
		imageUrl: '',
		website: 'https://corporate.walmart.com/',
	},
	BE0974349814: {
		exchange: exchanges.BRUSSELS,
		type: 'stock',
		industry: industries.REITIndustrial,
		tags: [assetTags.realEstate, assetTags.logistics, assetTags.warehouses],
		isActive: true,
		isin: 'BE0974349814',
		ticker: 'WDP',
		name: 'Warehouses De Pauw SA',
		shortName: 'Warehouses De Pauw',
		description: '',
		imageUrl: '',
		website: 'https://www.wdp.eu/',
	},
	SE0015657788: {
		exchange: exchanges.STOCKHOLM,
		type: 'stock',
		industry: industries.softwareInfrastructure,
		tags: [assetTags.technology, assetTags.cybersecurity],
		isActive: true,
		isin: 'SE0015657788',
		ticker: 'YUBICO',
		name: 'Yubico AB',
		shortName: 'Yubico',
		description: '',
		imageUrl: '',
		website: 'https://www.yubico.com',
	},
	US98923K1034: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.autoManufacturers,
		tags: [assetTags.automotive, assetTags.consumer, assetTags.technology],
		isActive: true,
		isin: 'US98923K1034',
		ticker: 'ZK',
		name: 'ZEEKR Intelligent Technology Holding Limited',
		shortName: 'ZEEKR Intelligent Technology Holding',
		description: '',
		imageUrl: '',
		website: 'https://www.zeekrlife.com/global/',
	},
	US98978V1035: {
		exchange: exchanges.NYSE,
		type: 'stock',
		industry: industries.drugManufacturersSpecialtyGeneric,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.veterinary,
		],
		isActive: true,
		isin: 'US98978V1035',
		ticker: 'ZTS',
		name: 'Zoetis Inc.',
		shortName: 'Zoetis',
		class: 'A',
		description: '',
		imageUrl: '',
		website: 'https://www.zoetis.com/',
	},
	// todo sold:
	// fortnox, k33, Lundin Gold
	// todo bitcoin, ethereum, cardano etc.
} as const satisfies Record<string, Asset>
