export const assetTags = {
	wasteAndRecycling: 'Waste & Recycling',
	skiing: 'Skiing',
	technology: 'Technology',
	industry: 'Industry',
	finance: 'Finance',
	banking: 'Banking',
	healthcare: 'Healthcare',
	consumer: 'Consumer',
	foodAndBeverages: 'Food & Beverages',
	paperAndForestProducts: 'Paper & Forest Products',
	energy: 'Energy',
	materials: 'Materials',
	realEstate: 'Real Estate',
	utilities: 'Utilities',
	telecom: 'Telecom',
	insurance: 'Insurance',
	defense: 'Defense',
	semiconductors: 'Semiconductors',
	hardware: 'Hardware',
	software: 'Software',
	cloud: 'Cloud',
	biotechnology: 'Biotechnology',
	pharmaceuticals: 'Pharmaceuticals',
	eCommerce: 'e-commerce',
	commercialVehicles: 'Commercial Vehicles',
	cybersecurity: 'Cybersecurity',
	automotive: 'Automotive',
	investmentCompanies: 'Investment Companies',
	crypto: 'Crypto',
	ai: 'AI',
	dataCenter: 'Data Center',
	retail: 'Retail',
	robotics: 'Robotics',
	travel: 'Travel',
	cannabis: 'Cannabis',
	payments: 'Payments',
	mining: 'Mining',
	nuclearEnergy: 'Nuclear Energy',
	logistics: 'Logistics',
	railroads: 'Railroads',
	transportation: 'Transportation',
	telecommunications: 'Telecommunications',
	fashion: 'Fashion',
	fintech: 'Fintech',
	gaming: 'Gaming',
	medicalDevices: 'Medical Devices',
	construction: 'Construction',
	entertainment: 'Entertainment',
	sports: 'Sports',
	hotelAndRestaurants: 'Hotel & Restaurants',
	warehouses: 'Warehouses',
	veterinary: 'Veterinary',
} as const

export type AssetTag = (typeof assetTags)[keyof typeof assetTags]
