export const assetTags = {
	technology: 'Technology',
	industry: 'Industry',
	finance: 'Finance',
	healthcare: 'Healthcare',
	consumer: 'Consumer',
	energy: 'Energy',
	materials: 'Materials',
	realEstate: 'Real Estate',
	utilities: 'Utilities',
	telecom: 'Telecom',
	insurance: 'Insurance',
	defense: 'Defense',
	semiconductors: 'Semiconductors',
	hardware: 'Hardware',
	software: 'Software',
	cloud: 'Cloud',
	biotechnology: 'Biotechnology',
	pharmaceuticals: 'Pharmaceuticals',
	eCommerce: 'e-commerce',
	commercialVehicles: 'Commercial Vehicles',
	cybersecurity: 'Cybersecurity',
	automotive: 'Automotive',
	investmentCompanies: 'Investment Companies',
	crypto: 'Crypto',
	ai: 'AI',
	dataCenter: 'Data Center',
	retail: 'Retail',
} as const

export type AssetTag = (typeof assetTags)[keyof typeof assetTags]
