import { AssetTag, assetTags } from './assetTags'
import { Industry, industries } from './industries'

export type Company = {
	name: string
	shortName: string
	description: string
	imageUrl?: string
	website: string
	industry: Industry
	tags: AssetTag[]
}

export const companies: Record<string, Company> = {
	ABB: {
		name: 'ABB Ltd',
		shortName: 'ABB',
		description: '',
		website: 'https://global.abb/group/en',
		industry: industries.electricalEquipmentParts,
		tags: [assetTags.technology, assetTags.industry, assetTags.robotics],
	},
	ASML: {
		name: 'ASML Holding N.V.',
		shortName: 'ASML Holding',
		description: '',
		website: 'https://www.asml.com/en',
		industry: industries.semiconductorEquipmentMaterials,
		tags: [
			assetTags.semiconductors,
			assetTags.industry,
			assetTags.technology,
			assetTags.hardware,
		],
	},
	AXA: {
		name: 'AXA SA',
		shortName: 'AXA',
		description: '',
		website: 'https://www.axa.com/',
		industry: industries.insuranceDiversified,
		tags: [assetTags.insurance, assetTags.finance],
	},
	AMD: {
		name: 'Advanced Micro Devices, Inc.',
		shortName: 'Advanced Micro Devices',
		description: '',
		website: 'https://www.amd.com/en.html',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
	},
	ABNB: {
		name: 'Airbnb, Inc.',
		shortName: 'Airbnb',
		description: '',
		website: 'https://www.airbnb.com/',
		industry: industries.travelServices,
		tags: [assetTags.technology, assetTags.software, assetTags.travel],
	},
	AIR: {
		name: 'Airbus SE',
		shortName: 'Airbus',
		description: '',
		website: 'https://www.airbus.com/en',
		industry: industries.aerospaceDefense,
		tags: [
			assetTags.industry,
			assetTags.defense,
			assetTags.technology,
			assetTags.commercialVehicles,
		],
	},
	BABA: {
		name: 'Alibaba Group Holding Limited',
		shortName: 'Alibaba Group',
		description: '',
		website: 'https://www.alibabagroup.com/en-US/',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.eCommerce,
			assetTags.consumer,
			assetTags.cloud,
			assetTags.ai,
		],
	},
	GOOGL: {
		name: 'Alphabet Inc.',
		shortName: 'Alphabet',
		description: '',
		website: 'https://abc.xyz/',
		industry: industries.internetContentInformation,
		tags: [assetTags.technology, assetTags.software, assetTags.cloud],
	},
	AMZN: {
		name: 'Amazon.com, Inc.',
		shortName: 'Amazon.com',
		description: '',
		website: 'https://www.aboutamazon.com/',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.cloud,
			assetTags.eCommerce,
		],
	},
	AAPL: {
		name: 'Apple Inc.',
		shortName: 'Apple',
		description: '',
		website: 'https://www.apple.com',
		industry: industries.consumerElectronics,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.cloud,
			assetTags.consumer,
			assetTags.hardware,
		],
	},
	AMAT: {
		name: 'Applied Materials, Inc.',
		shortName: 'Applied Materials',
		description: '',
		website: 'https://www.appliedmaterials.com/us/en.html',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
	},
	AZN: {
		name: 'AstraZeneca PLC',
		shortName: 'AstraZeneca',
		description: '',
		website: 'https://www.astrazeneca.com',
		industry: industries.drugManufacturersGeneral,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.healthcare,
		],
	},
	ATCO: {
		name: 'Atlas Copco AB',
		shortName: 'Atlas Copco',
		description: '',
		website: 'https://www.atlascopcogroup.com/',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.technology],
	},
	ACB: {
		name: 'Aurora Cannabis Inc.',
		shortName: 'Aurora Cannabis',
		description: '',
		website: 'https://www.auroramj.com/investors/',
		industry: industries.drugManufacturersSpecialtyGeneric,
		tags: [assetTags.cannabis, assetTags.pharmaceuticals],
	},
	AZA: {
		name: 'Avanza Bank Holding AB',
		shortName: 'Avanza Bank',
		description: '',
		website: 'https://www.avanza.se',
		industry: industries.banksRegional,
		tags: [assetTags.finance, assetTags.banking],
	},
	AXFO: {
		name: 'Axfood AB',
		shortName: 'Axfood',
		description: '',
		website: 'https://www.axfood.com/',
		industry: industries.groceryStores,
		tags: [assetTags.consumer],
	},
	BAHN: {
		name: 'Bahnhof AB',
		shortName: 'Bahnhof',
		description: '',
		website: 'https://bahnhof.se',
		industry: industries.telecomServices,
		tags: [assetTags.consumer, assetTags.telecom],
	},
	BNS: {
		name: 'The Bank of Nova Scotia',
		shortName: 'Bank of Nova Scotia',
		description: '',
		website: 'https://www.scotiabank.com',
		industry: industries.banksDiversified,
		tags: [assetTags.finance, assetTags.banking],
	},
	BIOA: {
		name: 'BioArctic AB',
		shortName: 'BioArctic',
		description: '',
		website: 'https://www.bioarctic.com/en/',
		industry: industries.biotechnology,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.healthcare,
		],
	},
	BLOCK: {
		name: 'Block, Inc.',
		shortName: 'Block',
		description: '',
		website: 'https://block.xyz/',
		industry: industries.softwareInfrastructure,
		tags: [
			assetTags.banking,
			assetTags.finance,
			assetTags.technology,
			assetTags.crypto,
			assetTags.software,
			assetTags.payments,
		],
	},
	AVGO: {
		name: 'Broadcom Inc.',
		shortName: 'Broadcom',
		description: '',
		website: 'https://www.broadcom.com',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
			assetTags.dataCenter,
		],
	},
	CCO: {
		name: 'Cameco Corporation',
		shortName: 'Cameco',
		description: '',
		website: 'https://www.cameco.com',
		industry: industries.uranium,
		tags: [assetTags.energy, assetTags.mining, assetTags.nuclearEnergy],
	},
	CNR: {
		name: 'Canadian National Railway Company',
		shortName: 'Canadian National Railway',
		description: '',
		website: 'https://www.cn.ca/en/',
		industry: industries.railroads,
		tags: [
			assetTags.transportation,
			assetTags.railroads,
			assetTags.logistics,
		],
	},
	CP: {
		name: 'Canadian Pacific Kansas City Limited',
		shortName: 'Canadian Pacific Kansas City',
		description: '',
		website: 'https://www.cpkcr.com/en',
		industry: industries.railroads,
		tags: [
			assetTags.transportation,
			assetTags.railroads,
			assetTags.logistics,
		],
	},
	CHECK: {
		name: 'Checkin.com Group AB',
		shortName: 'Checkin.com Group',
		description: '',
		website: 'https://group.checkin.com/',
		industry: industries.softwareApplication,
		tags: [assetTags.technology, assetTags.software],
	},
	CLAS: {
		name: 'Clas Ohlson AB',
		shortName: 'Clas Ohlson',
		description: '',
		website: 'https://www.clasohlson.com/',
		industry: industries.specialtyRetail,
		tags: [assetTags.consumer, assetTags.retail],
	},
	CLA: {
		name: 'Cloetta AB',
		shortName: 'Cloetta',
		description: '',
		website: 'https://www.cloetta.com',
		industry: industries.confectioners,
		tags: [assetTags.consumer, assetTags.foodAndBeverages],
	},
	KO: {
		name: 'The Coca-Cola Company',
		shortName: 'Coca-Cola',
		description: '',
		website: 'https://www.coca-colacompany.com',
		industry: industries.beveragesNonAlcoholic,
		tags: [assetTags.consumer, assetTags.foodAndBeverages],
	},
	COIN: {
		name: 'Coinbase Global, Inc.',
		shortName: 'Coinbase',
		description: '',
		website: 'https://www.coinbase.com',
		industry: industries.financialDataStockExchanges,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.finance,
			assetTags.crypto,
		],
	},
	CPNG: {
		name: 'Coupang, Inc.',
		shortName: 'Coupang',
		description: '',
		website: 'https://www.aboutcoupang.com',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.eCommerce,
			assetTags.consumer,
		],
	},
	CRED: {
		name: 'Creades AB',
		shortName: 'Creades',
		description: '',
		website: 'https://www.creades.se',
		industry: industries.assetManagement,
		tags: [assetTags.investmentCompanies, assetTags.finance],
	},
	CYCLE: {
		name: 'Cyclezyme AB',
		shortName: 'Cyclezyme',
		description: '',
		website: 'https://www.cyclezyme.se/',
		industry: industries.pollutionTreatmentControls,
		tags: [
			assetTags.technology,
			assetTags.wasteAndRecycling,
			assetTags.biotechnology,
			assetTags.materials,
			assetTags.industry,
		],
	},
	DSPW: {
		name: 'Doosan Skoda Power',
		shortName: 'Doosan Skoda Power',
		description: '',
		website: 'https://www.doosanskodapower.com/',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.technology],
	},
	FNOX: {
		name: 'Fortnox AB',
		shortName: 'Fortnox',
		description: '',
		website: 'https://www.fortnoxgroup.com/',
		industry: industries.softwareApplication,
		tags: [assetTags.technology, assetTags.software, assetTags.finance],
	},
	FORTUM: {
		name: 'Fortum Oyj',
		shortName: 'Fortum',
		description: '',
		website: 'https://www.fortum.com/Investors',
		industry: industries.utilitiesRegulatedElectric,
		tags: [assetTags.energy, assetTags.utilities, assetTags.nuclearEnergy],
	},
	GETI: {
		name: 'Getinge AB',
		shortName: 'Getinge',
		description: '',
		website: 'https://www.getinge.com',
		industry: industries.medicalDevices,
		tags: [assetTags.healthcare, assetTags.technology],
	},
	GRAB: {
		name: 'Grab Holdings Limited',
		shortName: 'Grab',
		description: '',
		website: 'https://www.grab.com/sg',
		industry: industries.softwareApplication,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.transportation,
		],
	},
	HEXA: {
		name: 'Hexagon AB',
		shortName: 'Hexagon',
		description: '',
		website: 'https://www.hexagon.com',
		industry: industries.scientificTechnicalInstruments,
		tags: [assetTags.industry, assetTags.technology],
	},
	HTRO: {
		name: 'Hexatronic Group AB',
		shortName: 'Hexatronic Group',
		description: '',
		website: 'https://www.hexatronic.com',
		industry: industries.communicationEquipment,
		tags: [assetTags.technology, assetTags.telecommunications],
	},
	HIMS: {
		name: 'Hims & Hers Health, Inc.',
		shortName: 'Hims & Hers Health',
		description: '',
		website: 'https://investors.hims.com/overview/default.aspx',
		industry: industries.householdPersonalProducts,
		tags: [assetTags.healthcare, assetTags.pharmaceuticals],
	},
	HUH1V: {
		name: 'Huhtamäki Oyj',
		shortName: 'Huhtamäki',
		description: '',
		website: 'https://www.huhtamaki.com/en/',
		industry: industries.packagingContainers,
		tags: [
			assetTags.consumer,
			assetTags.foodAndBeverages,
			assetTags.paperAndForestProducts,
		],
	},
	INVE: {
		name: 'Investor AB',
		shortName: 'Investor',
		description: '',
		website: 'https://www.investorab.com',
		industry: industries.assetManagement,
		tags: [assetTags.investmentCompanies, assetTags.finance],
	},
	K33: {
		name: 'K33 AB',
		shortName: 'K33',
		description: '',
		website: 'https://k33.com/',
		industry: industries.capitalMarkets,
		tags: [assetTags.crypto, assetTags.finance],
	},
	KNEBV: {
		name: 'Kone Oyj',
		shortName: 'Kone',
		description: '',
		website: 'https://www.kone.com/en/investors/',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.technology],
	},
	KEP: {
		name: 'Korea Electric Power Corporation',
		shortName: 'Korea Electric Power',
		description: '',
		website: 'https://home.kepco.co.kr/',
		industry: industries.utilitiesRegulatedElectric,
		tags: [assetTags.energy, assetTags.utilities, assetTags.nuclearEnergy],
	},
	LUG: {
		name: 'Lundin Gold Inc.',
		shortName: 'Lundin Gold',
		description: '',
		website: 'https://lundingold.com/',
		industry: industries.gold,
		tags: [assetTags.mining, assetTags.materials],
	},
	LUMI: {
		name: 'Lundin Mining Corporation',
		shortName: 'Lundin Mining Corporation',
		description: '',
		website: 'https://www.lundinmining.com/',
		industry: industries.copper,
		tags: [assetTags.mining, assetTags.materials],
	},
	MQ: {
		name: 'Marqeta, Inc.',
		shortName: 'Marqeta',
		description: '',
		website: 'https://www.marqeta.com',
		industry: industries.softwareInfrastructure,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.finance,
			assetTags.crypto,
			assetTags.payments,
		],
	},
	META: {
		name: 'Meta Platforms, Inc.',
		shortName: 'Meta Platforms',
		description: '',
		website: 'https://investor.atmeta.com/',
		industry: industries.internetContentInformation,
		tags: [assetTags.technology, assetTags.software],
	},
	MU: {
		name: 'Micron Technology, Inc.',
		shortName: 'Micron Technology',
		description: '',
		website: 'https://www.micron.com',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
	},
	MSFT: {
		name: 'Microsoft Corporation',
		shortName: 'Microsoft',
		description: '',
		website: 'https://www.microsoft.com',
		industry: industries.softwareInfrastructure,
		tags: [assetTags.technology, assetTags.software, assetTags.cloud],
	},
	MIPS: {
		name: 'Mips AB',
		shortName: 'Mips',
		description: '',
		website: 'https://mipscorp.com/',
		industry: industries.leisure,
		tags: [assetTags.hardware, assetTags.technology, assetTags.consumer],
	},
	NVDA: {
		name: 'NVIDIA Corporation',
		shortName: 'NVIDIA',
		description: '',
		website: 'https://www.nvidia.com/en-us/',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
	},
	NKE: {
		name: 'Nike, Inc.',
		shortName: 'Nike',
		description: '',
		website: 'https://www.nike.com',
		industry: industries.footwearAccessories,
		tags: [assetTags.consumer, assetTags.fashion],
	},
	NORION: {
		name: 'Norion Bank AB',
		shortName: 'Norion Bank',
		description: '',
		website: 'https://norionbank.se/',
		industry: industries.banksRegional,
		tags: [assetTags.banking, assetTags.finance],
	},
	NHY: {
		name: 'Norsk Hydro ASA',
		shortName: 'Norsk Hydro',
		description: '',
		website: 'https://www.hydro.com/en/en/',
		industry: industries.aluminum,
		tags: [assetTags.industry, assetTags.materials, assetTags.energy],
	},
	NOVO: {
		name: 'Novo Nordisk A/S',
		shortName: 'Novo Nordisk',
		description: '',
		website: 'https://www.novonordisk.com/',
		industry: industries.drugManufacturersGeneral,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.healthcare,
		],
	},
	NU: {
		name: 'Nu Holdings Ltd.',
		shortName: 'Nu Holdings',
		description: '',
		website: 'https://www.investidores.nu/en/',
		industry: industries.banksRegional,
		tags: [
			assetTags.banking,
			assetTags.finance,
			assetTags.payments,
			assetTags.fintech,
		],
	},
	OPRA: {
		name: 'Opera Limited',
		shortName: 'Opera',
		description: '',
		website: 'https://www.opera.com',
		industry: industries.internetContentInformation,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.fintech,
			assetTags.crypto,
		],
	},
	ORK: {
		name: 'Orkla ASA',
		shortName: 'Orkla',
		description: '',
		website: 'https://www.orkla.com/',
		industry: industries.packagedFoods,
		tags: [assetTags.consumer, assetTags.foodAndBeverages],
	},
	PAH3: {
		name: 'Porsche Automobil Holding SE',
		shortName: 'Porsche Automobil Holding',
		description: '',
		website: 'https://www.porsche-se.com/en/',
		industry: industries.autoManufacturers,
		tags: [assetTags.automotive, assetTags.industry, assetTags.consumer],
	},
	QCOM: {
		name: 'QUALCOMM Incorporated',
		shortName: 'QUALCOMM',
		description: '',
		website: 'https://www.qualcomm.com',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.hardware,
			assetTags.technology,
		],
	},
	RIVN: {
		name: 'Rivian Automotive, Inc.',
		shortName: 'Rivian Automotive',
		description: '',
		website: 'https://rivian.com/',
		industry: industries.autoManufacturers,
		tags: [assetTags.automotive, assetTags.industry, assetTags.consumer],
	},
	HOOD: {
		name: 'Robinhood Markets, Inc.',
		shortName: 'Robinhood Markets',
		description: '',
		website: 'https://robinhood.com/',
		industry: industries.capitalMarkets,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.finance,
			assetTags.crypto,
			assetTags.fintech,
		],
	},
	RYA: {
		name: 'Ryanair Holdings plc',
		shortName: 'Ryanair',
		description: '',
		website: 'https://www.ryanair.com/',
		industry: industries.airlines,
		tags: [assetTags.transportation, assetTags.travel],
	},
	SAAB: {
		name: 'Saab AB',
		shortName: 'SAAB',
		description: '',
		website: 'https://www.saab.com/',
		industry: industries.aerospaceDefense,
		tags: [assetTags.industry, assetTags.technology, assetTags.defense],
	},
	SKF: {
		name: 'AB SKF',
		shortName: 'SKF',
		description: '',
		website: 'https://www.skf.com/',
		industry: industries.toolsAccessories,
		tags: [assetTags.industry],
	},
	SFL: {
		name: 'Safello Group AB',
		shortName: 'Safello Group',
		description: '',
		website: 'https://safello.com/',
		industry: industries.softwareApplication,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.fintech,
			assetTags.crypto,
		],
	},
	CRM: {
		name: 'Salesforce, Inc.',
		shortName: 'Salesforce',
		description: '',
		website: 'https://www.salesforce.com/',
		industry: industries.softwareApplication,
		tags: [assetTags.technology, assetTags.software],
	},
	SAND: {
		name: 'Sandvik AB',
		shortName: 'Sandvik',
		description: '',
		website: 'https://www.home.sandvik/',
		industry: industries.specialtyIndustrialMachinery,
		tags: [assetTags.industry, assetTags.mining],
	},
	SE: {
		name: 'Sea Limited',
		shortName: 'Sea',
		description: '',
		website: 'https://www.sea.com/',
		industry: industries.internetRetail,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.fintech,
			assetTags.eCommerce,
			assetTags.payments,
			assetTags.gaming,
		],
	},
	SENZA: {
		name: 'SenzaGen AB',
		shortName: 'SenzaGen',
		description: '',
		website: 'https://senzagen.com/',
		industry: industries.diagnosticsResearch,
		tags: [
			assetTags.technology,
			assetTags.healthcare,
			assetTags.medicalDevices,
		],
	},
	SHOP: {
		name: 'Shopify Inc.',
		shortName: 'Shopify',
		description: '',
		website: 'https://www.shopify.com/',
		industry: industries.softwareApplication,
		tags: [
			assetTags.technology,
			assetTags.software,
			assetTags.eCommerce,
			assetTags.payments,
		],
	},
	SKA: {
		name: 'Skanska AB',
		shortName: 'Skanska',
		description: '',
		website: 'https://group.skanska.com/',
		industry: industries.engineeringConstruction,
		tags: [assetTags.construction],
	},
	SKIS: {
		name: 'SkiStar AB',
		shortName: 'SkiStar',
		description: '',
		website: 'https://www.skistar.com/',
		industry: industries.resortsCasinos,
		tags: [
			assetTags.travel,
			assetTags.consumer,
			assetTags.entertainment,
			assetTags.sports,
			assetTags.hotelAndRestaurants,
			assetTags.skiing,
		],
	},
	TSM: {
		name: 'Taiwan Semiconductor Manufacturing Company Limited',
		shortName: 'Taiwan Semicond Mfg Co',
		description: '',
		website: 'https://www.tsmc.com/english',
		industry: industries.semiconductors,
		tags: [
			assetTags.semiconductors,
			assetTags.industry,
			assetTags.technology,
			assetTags.hardware,
		],
	},
	TEL: {
		name: 'Telenor ASA',
		shortName: 'Telenor',
		description: '',
		website: 'https://www.telenor.com/',
		industry: industries.telecomServices,
		tags: [assetTags.telecom],
	},
	TSLA: {
		name: 'Tesla, Inc.',
		shortName: 'Tesla',
		description: '',
		website: 'https://www.tesla.com/',
		industry: industries.autoManufacturers,
		tags: [
			assetTags.automotive,
			assetTags.consumer,
			assetTags.technology,
			assetTags.robotics,
		],
	},
	THULE: {
		name: 'Thule Group AB',
		shortName: 'Thule Group',
		description: '',
		website: 'https://www.thulegroup.com/',
		industry: industries.leisure,
		tags: [assetTags.automotive, assetTags.consumer],
	},
	TOM: {
		name: 'Tomra Systems ASA',
		shortName: 'Tomra Systems',
		description: '',
		website: 'https://www.tomra.com/',
		industry: industries.wasteManagement,
		tags: [assetTags.technology, assetTags.wasteAndRecycling],
	},
	UBSG: {
		name: 'UBS Group AG',
		shortName: 'UBS Group',
		description: '',
		website: 'https://www.ubs.com/',
		industry: industries.banksDiversified,
		tags: [assetTags.banking, assetTags.finance],
	},
	UBER: {
		name: 'Uber Technologies, Inc.',
		shortName: 'Uber',
		description: '',
		website: 'https://www.uber.com',
		industry: industries.softwareApplication,
		tags: [assetTags.technology, assetTags.software],
	},
	VOLV: {
		name: 'AB Volvo',
		shortName: 'Volvo',
		description: '',
		website: 'https://www.volvogroup.com/',
		industry: industries.farmHeavyConstructionMachinery,
		tags: [assetTags.industry, assetTags.commercialVehicles],
	},
	WMT: {
		name: 'Walmart Inc.',
		shortName: 'Walmart',
		description: '',
		website: 'https://corporate.walmart.com/',
		industry: industries.discountStores,
		tags: [
			assetTags.retail,
			assetTags.consumer,
			assetTags.foodAndBeverages,
		],
	},
	WDP: {
		name: 'Warehouses De Pauw SA',
		shortName: 'Warehouses De Pauw',
		description: '',
		website: 'https://www.wdp.eu/',
		industry: industries.REITIndustrial,
		tags: [assetTags.realEstate, assetTags.logistics, assetTags.warehouses],
	},
	YUBICO: {
		name: 'Yubico AB',
		shortName: 'Yubico',
		description: '',
		website: 'https://www.yubico.com',
		industry: industries.softwareInfrastructure,
		tags: [assetTags.technology, assetTags.cybersecurity],
	},
	ZK: {
		name: 'ZEEKR Intelligent Technology Holding Limited',
		shortName: 'ZEEKR Intelligent Technology Holding',
		description: '',
		website: 'https://www.zeekrlife.com/global/',
		industry: industries.autoManufacturers,
		tags: [assetTags.automotive, assetTags.consumer, assetTags.technology],
	},
	ZTS: {
		name: 'Zoetis Inc.',
		shortName: 'Zoetis',
		description: '',
		website: 'https://www.zoetis.com/',
		industry: industries.drugManufacturersSpecialtyGeneric,
		tags: [
			assetTags.pharmaceuticals,
			assetTags.biotechnology,
			assetTags.veterinary,
		],
	},
} as const satisfies Record<string, Company>
