import { type Currency, currencies } from './currencies'

export type Exchange = {
	MIC: string
	name: string
	shortName: string
	code?: string
	codeAlt?: string
	timezoneName: string
	timezoneShortName: string
	currency: Currency
	country: string
	city: string
	website: string
	emoji: string
}

export const exchanges: Record<string, Exchange> = {
	STOCKHOLM: {
		MIC: 'XSTO',
		name: 'Nasdaq Stockholm',
		shortName: 'Stockholm',
		code: 'STO',
		codeAlt: 'ST',
		timezoneName: 'Europe/Stockholm',
		timezoneShortName: 'CEST',
		currency: currencies.SEK,
		country: 'Sweden',
		city: 'Stockholm',
		website: 'https://www.nasdaq.com/solutions/european-markets/stockholm',
		emoji: '🇸🇪',
	},
	SPOTLIGHT: {
		MIC: 'XSAT',
		name: 'Spotlight Stockholm',
		shortName: 'Spotlight',
		code: 'STO',
		codeAlt: 'ST',
		timezoneName: 'Europe/Stockholm',
		timezoneShortName: 'CEST',
		currency: currencies.SEK,
		country: 'Sweden',
		city: 'Stockholm',
		website: 'https://www.spotlightstockmarket.com/',
		emoji: '🇸🇪',
	},
	COPENHAGEN: {
		MIC: 'XCSE',
		name: 'Nasdaq Copenhagen',
		shortName: 'Copenhagen',
		code: 'COP',
		codeAlt: 'CO',
		timezoneName: 'Europe/Copenhagen',
		timezoneShortName: 'CEST',
		currency: currencies.DKK,
		country: 'Denmark',
		city: 'Copenhagen',
		website: 'https://www.nasdaq.com/solutions/european-markets/copenhagen',
		emoji: '🇩🇰',
	},
	HELSINKI: {
		MIC: 'XHEL',
		name: 'Nasdaq Helsinki',
		shortName: 'Helsinki',
		code: 'HEL',
		codeAlt: 'HE',
		timezoneName: 'Europe/Helsinki',
		timezoneShortName: 'EEST',
		currency: currencies.EUR,
		country: 'Finland',
		city: 'Helsinki',
		website: 'https://www.nasdaq.com/solutions/european-markets/helsinki',
		emoji: '🇫🇮',
	},
	AMSTERDAM: {
		MIC: 'XAMS',
		name: 'Euronext Amsterdam',
		shortName: 'Amsterdam',
		code: 'AMS',
		codeAlt: 'AS',
		timezoneName: 'Europe/Amsterdam',
		timezoneShortName: 'CEST',
		currency: currencies.EUR,
		country: 'Netherlands',
		city: 'Amsterdam',
		website: 'https://www.euronext.com/en/markets/amsterdam',
		emoji: '🇳🇱',
	},
	PARIS: {
		MIC: 'XPAR',
		name: 'Euronext Paris',
		shortName: 'Paris',
		code: 'PAR',
		codeAlt: 'PA',
		timezoneName: 'Europe/Paris',
		timezoneShortName: 'CEST',
		currency: currencies.EUR,
		country: 'France',
		city: 'Paris',
		website: 'https://www.euronext.com/en/markets/paris',
		emoji: '🇫🇷',
	},
	XETRA: {
		MIC: 'XETR',
		name: 'XETRA',
		shortName: 'XETRA',
		code: 'GER',
		codeAlt: 'DE',
		timezoneName: 'Europe/Berlin',
		timezoneShortName: 'CEST',
		currency: currencies.EUR,
		country: 'Germany',
		city: 'Frankfurt',
		website: 'https://www.xetra.com/xetra-en',
		emoji: '🇩🇪',
	},
	NYSE: {
		MIC: 'XNYS',
		name: 'New York Stock Exchange',
		shortName: 'NYSE',
		// code:
		// codeAlt:
		timezoneName: 'America/New_York',
		timezoneShortName: 'EDT',
		currency: currencies.USD,
		country: 'United States',
		city: 'New York',
		website: 'https://www.nyse.com/',
		emoji: '🇺🇸',
	},
	NASDAQ: {
		MIC: 'XNAS',
		name: 'NASDAQ - All Markets',
		shortName: 'NASDAQ',
		// code:
		// codeAlt:
		timezoneName: 'America/New_York',
		timezoneShortName: 'EDT',
		currency: currencies.USD,
		country: 'United States',
		city: 'New York',
		website: 'https://www.nasdaq.com/',
		emoji: '🇺🇸',
	},
	TORONTO: {
		MIC: 'XTSE',
		name: 'Toronto Stock Exchange',
		shortName: 'TSX',
		code: 'TOR',
		codeAlt: 'TO',
		timezoneName: 'America/Toronto',
		timezoneShortName: 'EDT',
		currency: currencies.CAD,
		country: 'Canada',
		city: 'Toronto',
		website: 'https://www.tsx.com/',
		emoji: '🇨🇦',
	},
	PRAGUE: {
		MIC: 'XPRA',
		name: 'Prague Stock Exchange',
		shortName: 'PSE',
		code: 'PRA',
		codeAlt: 'PR',
		timezoneName: 'Europe/Prague',
		timezoneShortName: 'CEST',
		currency: currencies.CZK,
		country: 'Czechia',
		city: 'Prague',
		website: 'https://www.pse.cz/',
		emoji: '🇨🇿',
	},
	OSLO: {
		MIC: 'XOSL',
		name: 'Oslo Børs',
		shortName: 'Oslo Børs',
		code: 'OSL',
		codeAlt: 'OS',
		timezoneName: 'Europe/Oslo',
		timezoneShortName: 'CEST',
		currency: currencies.NOK,
		country: 'Norway',
		city: 'Oslo',
		website: 'https://www.oslobors.no/',
		emoji: '🇳🇴',
	},
	DUBLIN: {
		MIC: 'XDUB',
		name: 'Irish Stock Exchange',
		shortName: 'ISE',
		code: 'ISE',
		codeAlt: 'IR',
		timezoneName: 'Europe/Dublin',
		timezoneShortName: 'IST',
		currency: currencies.EUR,
		country: 'Ireland',
		city: 'Dublin',
		website: 'https://www.ise.ie/',
		emoji: '🇮🇪',
	},
	SWISS: {
		MIC: 'XSWX',
		name: 'SIX Swiss Exchange',
		shortName: 'Swiss Exchange',
		code: 'EBS',
		codeAlt: 'SW',
		timezoneName: 'Europe/Zurich',
		timezoneShortName: 'CEST',
		currency: currencies.CHF,
		country: 'Switzerland',
		city: 'Zurich',
		website: 'https://www.six-group.com/en/site/exchanges.html',
		emoji: '🇨🇭',
	},
	BRUSSELS: {
		MIC: 'XBRU',
		name: 'Euronext Brussels',
		shortName: 'Brussels',
		code: 'BRU',
		codeAlt: 'BR',
		timezoneName: 'Europe/Brussels',
		timezoneShortName: 'CEST',
		currency: currencies.EUR,
		country: 'Belgium',
		city: 'Brussels',
		website: 'https://www.euronext.com/en/markets/brussels',
		emoji: '🇧🇪',
	},
}
