export const industries = {
	// Technology
	semiconductors: 'Semiconductors',
	softwareInfrastructure: 'Software - Infrastructure',
	consumerElectronics: 'Consumer Electronics',
	softwareApplication: 'Software - Application',
	semiconductorEquipmentMaterials: 'Semiconductor Equipment & Materials',
	informationTechnologyServices: 'Information Technology Services',
	computerHardware: 'Computer Hardware',
	communicationEquipment: 'Communication Equipment',
	electronicComponents: 'Electronic Components',
	scientificTechnicalInstruments: 'Scientific & Technical Instruments',
	solar: 'Solar',
	electronicsComputerDistribution: 'Electronics & Computer Distribution',

	// Financial Services
	banksDiversified: 'Banks - Diversified',
	creditServices: 'Credit Services',
	assetManagement: 'Asset Management',
	insuranceDiversified: 'Insurance - Diversified',
	banksRegional: 'Banks - Regional',
	capitalMarkets: 'Capital Markets',
	financialDataStockExchanges: 'Financial Data & Stock Exchanges',
	insurancePropertyCasualty: 'Insurance - Property & Casualty',
	insuranceBrokers: 'Insurance Brokers',
	insuranceLife: 'Insurance - Life',
	insuranceSpecialty: 'Insurance - Specialty',
	mortgageFinance: 'Mortgage Finance',
	insuranceReinsurance: 'Insurance - Reinsurance',
	financialConglomerates: 'Financial Conglomerates',
	shellCompanies: 'Shell Companies',

	// Consumer Cyclical
	internetRetail: 'Internet Retail',
	autoManufacturers: 'Auto Manufacturers',
	restaurants: 'Restaurants',
	homeImprovementRetail: 'Home Improvement Retail',
	travelServices: 'Travel Services',
	apparelRetail: 'Apparel Retail',
	autoParts: 'Auto Parts',
	specialtyRetail: 'Specialty Retail',
	packagingContainers: 'Packaging & Containers',
	residentialConstruction: 'Residential Construction',
	lodging: 'Lodging',
	gambling: 'Gambling',
	resortsCasinos: 'Resorts & Casinos',
	footwearAccessories: 'Footwear & Accessories',
	autoTruckDealerships: 'Auto Truck Dealerships',
	leisure: 'Leisure',
	apparelManufacturing: 'Apparel Manufacturing',
	personalServices: 'Personal Services',
	furnishingsFixturesAppliances: 'Furnishings, Fixtures & Appliances',
	luxuryGoods: 'Luxury Goods',
	recreationalVehicles: 'Recreational Vehicles',
	departmentStores: 'Department Stores',
	textileManufacturing: 'Textile Manufacturing',

	// Communication Services
	internetContentInformation: 'Internet Content & Information',
	telecomServices: 'Telecom Services',
	entertainment: 'Entertainment',
	electronicGamingMultimedia: 'Electronic Gaming & Multimedia',
	advertisingAgencies: 'Advertising Agencies',
	broadcasting: 'Broadcasting',
	publishing: 'Publishing',

	// Healthcare
	drugManufacturersGeneral: 'Drug Manufacturers - General',
	medicalDevices: 'Medical Devices',
	biotechnology: 'Biotechnology',
	healthcarePlans: 'Healthcare Plans',
	diagnosticsResearch: 'Diagnostics & Research',
	medicalInstrumentsSupplies: 'Medical Instruments & Supplies',
	medicalCareFacilities: 'Medical Care Facilities',
	medicalDistribution: 'Medical Distribution',
	drugManufacturersSpecialtyGeneric:
		'Drug Manufacturers - Specialty & Generic',
	healthInformationServices: 'Health Information Services',
	pharmaceuticalRetailers: 'Pharmaceutical Retailers',

	// Industrials
	aerospaceDefense: 'Aerospace & Defense',
	specialtyIndustrialMachinery: 'Specialty Industrial Machinery',
	railroads: 'Railroads',
	farmHeavyConstructionMachinery: 'Farm & Heavy Construction Machinery',
	buildingProductsEquipment: 'Building Products & Equipment',
	specialityBusinessServices: 'Speciality Business Services',
	wasteManagement: 'Waste Management',
	industrialDistribution: 'Industrial Distribution',
	integratedFreightLogistics: 'Integrated Freight & Logistics',
	conglomerates: 'Conglomerates',
	rentalLeasingServices: 'Rental & Leasing Services',
	airlines: 'Airlines',
	trucking: 'Trucking',
	engineeringConstruction: 'Engineering & Construction',
	electricalEquipmentParts: 'Electrical & Equipment Parts',
	consultingServices: 'Consulting Services',
	toolsAccessories: 'Tools & Accessories',
	metalFabrication: 'Metal Fabrication',
	pollutionTreatmentControls: 'Pollution & Treatment Controls',
	securityProtectionServices: 'Security & Protection Services',
	infrastructureOperations: 'Infrastructure Operations',
	staffingEmploymentServices: 'Staffing & Employment Services',
	marineShipping: 'Marine Shipping',
	airportsAirServices: 'Airports & Air Services',
	businessEquipmentSupplies: 'Business Equipment & Supplies',

	// Consumer Defensive
	discountStores: 'Discount Stores',
	householdPersonalProducts: 'Household & Personal Products',
	beveragesNonAlcoholic: 'Beverages - Non-Alcoholic',
	tobacco: 'Tobacco',
	packagedFoods: 'Packaged Foods',
	confectioners: 'Confectioners',
	foodDistribution: 'Food Distribution',
	groceryStores: 'Grocery Stores',
	beveragesBrewers: 'Beverages - Brewers',
	beveragesWineriesDistilleries: 'Beverages - Wineries & Distilleries',
	educationTrainingServices: 'Education & Training Services',

	// Energy
	oilGasIntegrated: 'Oil & Gas Integrated',
	oilGasMidstream: 'Oil & Gas Midstream',
	oilGasEP: 'Oil & Gas EP',
	oilGasEquipmentServices: 'Oil & Gas Equipment & Services',
	oilGasRefiningMarketing: 'Oil & Gas Refining & Marketing',
	oilGasDrilling: 'Oil & Gas & Drilling',
	uranium: 'Uranium',
	thermalCoal: 'Thermal Coal',

	// Real Estate
	REITSpeciality: 'REIT - Speciality',
	REITIndustrial: 'REIT - Industrial',
	REITRetail: 'REIT - Retail',
	REITResidential: 'REIT - Residential',
	REITHealthcareFacilities: 'REIT - Healthcare Facilities',
	REITOffice: 'REIT - Office',
	REITMortgage: 'REIT - Mortgage',
	REITDiversified: 'REIT - Diversified',
	REITHotelMotel: 'REIT - Hotel & Motel',
	RealEstateServices: 'Real Estate Services',
	realEstateDiversified: 'Real Estate - Diversified',
	realEstateDevelopment: 'Real Estate - Development',

	// Basic Materials
	specialtyChemicals: 'Specialty Chemicals',
	gold: 'Gold',
	copper: 'Copper',
	buildingMaterials: 'Building Materials',
	argriculturalInputs: 'Argricultural Inputs',
	steel: 'Steel',
	chemicals: 'Chemicals',
	otherIndustrialMetalsMining: 'Other Industrial Metals & Mining',
	lumberWoodProduction: 'Lumber & Wood Production',
	aluminum: 'Aluminum',
	otherPreciousMetalsMining: 'Other Precious Metals & Mining',
	silver: 'Silver',
	cokingCoal: 'Coking Coal',
	paperPaperProducts: 'Paper & Paper Products',

	// Utilities
	utilitiesRegulatedElectric: 'Utilities - Regulated Electric',
	utilitiesRenewable: 'Utilities - Renewable',
	utilitiesIndependentPowerProducers:
		'Utilities - Independent Power Producers',
	utilitiesDiversified: 'Utilities - Diversified',
	utilitiesRegulatedGas: 'Utilities - Regulated Gas',
	utilitiesRegulatedWater: 'Utilities - Regulated Water',
} as const

export type Industry = (typeof industries)[keyof typeof industries]
