import { type Industry, industries } from './industries'

export type Sector = {
	name: string
	industries: Industry[]
}

export const sectors = {
	technology: {
		name: 'Technology',
		industries: [
			industries.semiconductors,
			industries.softwareInfrastructure,
			industries.consumerElectronics,
			industries.softwareApplication,
			industries.semiconductorEquipmentMaterials,
			industries.computerHardware,
			industries.communicationEquipment,
			industries.electronicComponents,
			industries.scientificTechnicalInstruments,
			industries.solar,
			industries.electronicsComputerDistribution,
		],
	},
	financialServices: {
		name: 'Financial Services',
		industries: [
			industries.banksDiversified,
			industries.creditServices,
			industries.assetManagement,
			industries.insuranceDiversified,
			industries.banksRegional,
			industries.capitalMarkets,
			industries.financialDataStockExchanges,
			industries.insurancePropertyCasualty,
			industries.insuranceBrokers,
			industries.insuranceLife,
			industries.insuranceSpecialty,
			industries.mortgageFinance,
			industries.insuranceReinsurance,
			industries.financialConglomerates,
			industries.shellCompanies,
		],
	},
	consumerCyclical: {
		name: 'Consumer Cyclical',
		industries: [
			industries.internetRetail,
			industries.autoManufacturers,
			industries.restaurants,
			industries.homeImprovementRetail,
			industries.travelServices,
			industries.apparelRetail,
			industries.autoParts,
			industries.specialtyRetail,
			industries.packagingContainers,
			industries.residentialConstruction,
			industries.lodging,
			industries.gambling,
			industries.resortsCasinos,
			industries.footwearAccessories,
			industries.autoTruckDealerships,
			industries.leisure,
			industries.apparelManufacturing,
			industries.personalServices,
			industries.furnishingsFixturesAppliances,
			industries.luxuryGoods,
			industries.recreationalVehicles,
			industries.departmentStores,
			industries.textileManufacturing,
		],
	},
	communicationServices: {
		name: 'Communication Services',
		industries: [
			industries.internetContentInformation,
			industries.telecomServices,
			industries.entertainment,
			industries.electronicGamingMultimedia,
			industries.advertisingAgencies,
			industries.broadcasting,
			industries.publishing,
		],
	},
	healthcare: {
		name: 'Healthcare',
		industries: [
			industries.drugManufacturersGeneral,
			industries.medicalDevices,
			industries.biotechnology,
			industries.healthcarePlans,
			industries.diagnosticsResearch,
			industries.medicalInstrumentsSupplies,
			industries.medicalCareFacilities,
			industries.medicalDistribution,
			industries.drugManufacturersSpecialtyGeneric,
			industries.healthInformationServices,
			industries.pharmaceuticalRetailers,
		],
	},
	industrials: {
		name: 'Industrials',
		industries: [
			industries.aerospaceDefense,
			industries.specialtyIndustrialMachinery,
			industries.railroads,
			industries.farmHeavyConstructionMachinery,
			industries.buildingProductsEquipment,
			industries.specialityBusinessServices,
			industries.wasteManagement,
			industries.industrialDistribution,
			industries.integratedFreightLogistics,
			industries.conglomerates,
			industries.rentalLeasingServices,
			industries.airlines,
			industries.trucking,
			industries.engineeringConstruction,
			industries.electricalEquipmentParts,
			industries.consultingServices,
			industries.toolsAccessories,
			industries.metalFabrication,
			industries.pollutionTreatmentControls,
			industries.securityProtectionServices,
			industries.infrastructureOperations,
			industries.staffingEmploymentServices,
			industries.marineShipping,
			industries.airportsAirServices,
			industries.businessEquipmentSupplies,
		],
	},
	consumerDefensive: {
		name: 'Consumer Defensive',
		industries: [
			industries.discountStores,
			industries.householdPersonalProducts,
			industries.beveragesNonAlcoholic,
			industries.tobacco,
			industries.packagedFoods,
			industries.confectioners,
			industries.foodDistribution,
			industries.groceryStores,
			industries.beveragesBrewers,
			industries.beveragesWineriesDistilleries,
			industries.educationTrainingServices,
		],
	},
	energy: {
		name: 'Energy',
		industries: [
			industries.oilGasIntegrated,
			industries.oilGasMidstream,
			industries.oilGasEP,
			industries.oilGasEquipmentServices,
			industries.oilGasRefiningMarketing,
			industries.oilGasDrilling,
			industries.uranium,
			industries.thermalCoal,
		],
	},
	realEstate: {
		name: 'Real Estate',
		industries: [
			industries.REITSpeciality,
			industries.REITIndustrial,
			industries.REITRetail,
			industries.REITResidential,
			industries.REITHealthcareFacilities,
			industries.REITOffice,
			industries.REITMortgage,
			industries.REITDiversified,
			industries.REITHotelMotel,
			industries.RealEstateServices,
			industries.realEstateDiversified,
			industries.realEstateDevelopment,
		],
	},
	basicMaterials: {
		name: 'Basic Materials',
		industries: [
			industries.specialtyChemicals,
			industries.gold,
			industries.copper,
			industries.buildingMaterials,
			industries.argriculturalInputs,
			industries.steel,
			industries.chemicals,
			industries.otherIndustrialMetalsMining,
			industries.lumberWoodProduction,
			industries.aluminum,
			industries.otherPreciousMetalsMining,
			industries.silver,
			industries.cokingCoal,
			industries.paperPaperProducts,
		],
	},
	utilities: {
		name: 'Utilities',
		industries: [
			industries.utilitiesRegulatedElectric,
			industries.utilitiesRenewable,
			industries.utilitiesIndependentPowerProducers,
			industries.utilitiesDiversified,
			industries.utilitiesRegulatedGas,
			industries.utilitiesRegulatedWater,
		],
	},
} as const satisfies Record<string, Sector>
