services:
    backend:
        build:
            context: .
            dockerfile: server/Dockerfile
        restart: unless-stopped
        environment:
            NODE_ENV: production

    caddy:
        image: caddy:2
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
